language: node_js
dist: trusty
notifications:
  email: false
before_script: npm run greenkeeper:update-lockfile
after_script: npm run greenkeeper:upload-lockfile
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
  - secure: Z1hK4kFewmIoYYjSMMwFQ25q2ErheidK618XQmHgyBhElr0MbB5fyM4kajB7Juf3o5QLgb34dZEbVHLki3zuY5npNrZ/DI+1nkJBxtoj1+/aBjGzrRMv6VB+UipgSNC9bdjpwBHUvKfF7Tw2kDLTtwu5nbG+rZFe1oYWQKDvuGnMA6tg+4K9aYaZz06Bzx2gLpXLhd03aH4CxcHGouXnWb75D8NeVKHseDrW5emZVa54jD+jepoLUhsPud9jvzsr/e8ejLr6H78QMzmJdG8iEigDUuRmhDNyJHmaYD3IDh6VOr617Qhr/Oui9jDLj+jOAnHCdQxf4kDOsWe3c+FbA6mjKWDve1oIY4ND2Utawu4MHWrOr2zlAfmBPsRUo5cCPiiWXSBMjXLrSwjRENT48wZF62rj+MJv4r/XxkUVxNtHf8MtvUlYrJGYSxjMQTUUGdahBON++dAgDYgKCRr4Kt0G5xoaGDwnv4K3kaKeY0SfGkk/qVBwRxjTN6q5fW0P/JK0vJG4f4QDsJxLcCZN3TOhps5OVzPhmbHWCC5jUX9pLbt3G56gkseEVXeQJCA9n3zpQ1IlL5OYMoFv4CmMUdZuluoyygnakkk1jDRGoIkN29utcT+Rz4VYmM43igTMVNxI+8G6R1s8/bwjWGDClWaWL6NP4JKevPjK16ERt10=
